#!/bin/bash
TARGET=$1
TARGET_FILES=$(find $1 -type f)
TMP=$(mktemp -d)
echo "SHA256_SUM,BASENAME,FULL_PATH" > $TMP/inv.csv
recon () {
  RECON_TARGET=$1
  SHA256_SUM=$(sha256sum $RECON_TARGET| awk '{print $1}')
  FULL_PATH=$(realpath $RECON_TARGET)
  BASENAME=$(basename $RECON_TARGET)
  #echo "$BASENAME,$SHA256_SUM,$FULL_PATH" >> $TMP/inv.csv
  echo "$SHA256_SUM,$BASENAME,$FULL_PATH" >> $TMP/inv.csv
}
for i in $TARGET_FILES; do recon $i;done
cat $TMP/inv.csv
rm $TMP/inv.csv
rmdir $TMP
