#!/bin/bash
THIS_CWD=$(pwd)
TARGET=$1

TMP=$(mktemp -d)
echo "SHA256_SUM,BASENAME,FULL_PATH" > $TMP/inv.csv
recon () {
  RECON_TARGET=$1
  if [[ -f "$RECON_TARGET" ]]; then
    SHA256_SUM=$(sha256sum "$RECON_TARGET"| awk '{print $1}')
    FULL_PATH=$(realpath "$RECON_TARGET")
    BASENAME=$(basename "$RECON_TARGET")
    echo "$SHA256_SUM,$BASENAME,$FULL_PATH" >> $TMP/inv.csv
  else
    echo "$RECON_TARGET is not a file"
  fi
}


find $TARGET -type f -print0 | while IFS= read -r -d '' file; do
    recon "$file"
done
mv -iv $TMP/inv.csv $THIS_CWD/
rmdir $TMP
ls -alh $THIS_CWD/inv.csv
